export interface UserAddress {
  id: string;
  school_id: string;
  teacher_id: string;
  address1: string;
  address2: string;
  country: string | number;
  state: string | number;
  city: string | number;
  postal_code: string;
  address_type: string | number;
  same_permanent: string | number;
  status: string | number;
  created_at?: string;
  updated_at?: string;
  country_name: string;
  state_name: string;
  city_name: string;
}

export interface UserData {
  id: string | number;
  school_id?: string | number;
  school_name?: string;
  schoolName?: string;
  first_name?: string;
  firstName?: string;
  last_name?: string;
  lastName?: string;
  name?: string;
  email?: string;
  email_address?: string;
  school_email?: string;
  phone?: string;
  primary_contact_number?: string;
  picture?: string;
  gender?: string | number;
  gender_name?: string;
  date_of_joining?: string;
  dateOfJoining?: string;
  joining_date?: string;
  qualification?: string;
  father_name?: string;
  mother_name?: string;
  status?: string | number;
  date_of_birth?: string;
  dateOfBirth?: string;
  dob?: string;
  religion?: string;
  emergency_phone?: string;
  present_address?: string;
  permanent_address?: string;
  role_name?: string;
  roleName?: string;
  national_id?: string;
  teacherId?: string;
  teacher_id?: string;
  blood_group?: string | number;
  bloodGroup?: string | number;
  blood_group_name?: string;
  bloodGroupName?: string;
  marital_status?: string | number;
  maritalStatus?: string | number;
  marital_status_name?: string;
  maritalStatusName?: string;
  language_known?: string;
  work_experience?: string;
  workExperience?: string;
  pan_number?: string;
  address?: UserAddress[] | any;
  address1?: string;
  address2?: string;
  country?: string | number;
  country_name?: string;
  countryName?: string;
  state?: string | number;
  state_name?: string;
  stateName?: string;
  city?: string | number;
  city_name?: string;
  cityName?: string;
  postal_code?: string;
  postalCode?: string;
  class_name?: string;
  className?: string;
  section_name?: string;
  sectionName?: string;
  subject_name?: string;
  subjectName?: string;
  classAssignments?: any[];
  token?: string;
}

export interface AuthState {
  user: UserData | null;
  token: string | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  error: string | null;
}
